name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [vanilla, react, vue, angular]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install
        run: pnpm install --frozen-lockfile=false

      - name: Format check
        run: pnpm run format:check

      - name: Lint (vanilla)
        if: matrix.app == 'vanilla'
        run: pnpm run lint

      - name: Lint (react)
        if: matrix.app == 'react'
        run: pnpm -F @ss-qa/react run lint

      - name: Lint (vue)
        if: matrix.app == 'vue'
        run: pnpm -F @ss-qa/vue run lint

      - name: Lint (angular)
        if: matrix.app == 'angular'
        run: pnpm -F @ss-qa/angular run lint

      - name: Test (vanilla, with coverage)
        if: matrix.app == 'vanilla'
        run: pnpm run coverage:vanilla

      - name: Test (react with coverage)
        if: matrix.app == 'react'
        run: pnpm -F @ss-qa/react run coverage

      - name: Test (vue with coverage)
        if: matrix.app == 'vue'
        run: pnpm -F @ss-qa/vue run coverage

      - name: Test (angular)
        if: matrix.app == 'angular'
        run: pnpm -F @ss-qa/angular run test:ci

      - name: Build app
        run: pnpm -F @ss-qa/${{ matrix.app }} build

      - name: Upload coverage (vanilla)
        if: matrix.app == 'vanilla' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: apps/vanilla/coverage
          if-no-files-found: ignore

      - name: Upload coverage (react)
        if: matrix.app == 'react' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-react
          path: apps/react/coverage
          if-no-files-found: ignore

      - name: Upload coverage (vue)
        if: matrix.app == 'vue' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-vue
          path: apps/vue/coverage
          if-no-files-found: ignore

      - name: Upload dist (vanilla/vue/angular)
        if: (matrix.app == 'vanilla' || matrix.app == 'vue' || matrix.app == 'angular') && always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.app }}
          path: apps/${{ matrix.app }}/dist
          if-no-files-found: ignore

      - name: Upload .next (react)
        if: matrix.app == 'react' && always()
        uses: actions/upload-artifact@v4
        with:
          name: next-react
          path: apps/react/.next
          if-no-files-found: ignore
